FROM python:2.7.12

RUN pip install flask \
                flask-restful \
                requests \
                MySQL-python \
                xmltodict \
                lxml \
                beautifulsoup4 \
                redis \
                pymysql

EXPOSE 5000
