SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `thousandEyes`
--

CREATE TABLE `statistics` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`endpoint` TEXT NOT NULL,
	`timerequest` FLOAT NOT NULL,
	`timeresponse` FLOAT NOT NULL,
	PRIMARY KEY (`ID`)
);

